-- ============================================================
--  Naï Beauty : configuration Supabase
--  Modèle simple : accès public en lecture ET écriture.
--  L'admin est protégé côté site par le code PIN (pas d'auth email).
--  Ce script est ré-exécutable sans risque (idempotent).
-- ============================================================

-- 1) Table des produits
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  price numeric not null default 0,
  image text,
  category text,
  created_at timestamptz not null default timezone('utc', now())
);

-- 2) Table du contenu de l'accueil (une seule ligne, id = 1)
create table if not exists public.site_content (
  id integer primary key default 1 check (id = 1),
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Ligne initiale (vide) du contenu du site
insert into public.site_content (id, content)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

-- 3) Écritures ouvertes (pas d'authentification)
alter table public.products disable row level security;
alter table public.site_content disable row level security;

-- 4) Stockage des images (bucket public "images")
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

-- On repart de zéro sur les policies du bucket pour éviter les doublons
drop policy if exists "Public can read images" on storage.objects;
drop policy if exists "Anyone can upload images" on storage.objects;
drop policy if exists "Anyone can update images" on storage.objects;
drop policy if exists "Anyone can delete images" on storage.objects;

create policy "Public can read images"
on storage.objects for select
using (bucket_id = 'images');

create policy "Anyone can upload images"
on storage.objects for insert
with check (bucket_id = 'images');

create policy "Anyone can update images"
on storage.objects for update
using (bucket_id = 'images')
with check (bucket_id = 'images');

create policy "Anyone can delete images"
on storage.objects for delete
using (bucket_id = 'images');
