create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  price numeric not null,
  image text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Désactiver la sécurité RLS pour l'instant afin de faciliter vos tests
alter table public.products disable row level security;