create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  price numeric not null default 0,
  image text,
  category text,
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id integer primary key default 1 check (id = 1),
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.site_content enable row level security;

create policy "Public can read products" on public.products for select using (true);
create policy "Admin can manage products" on public.products for all using (true) with check (true);
create policy "Public can read site content" on public.site_content for select using (true);
create policy "Admin can manage site content" on public.site_content for all using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

create policy "Public can read images" on storage.objects for select using (bucket_id = 'images');
create policy "Public can upload images" on storage.objects for insert with check (bucket_id = 'images');